// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8PJO6vZlY4CeRriyuOpcoxcuK6q0xLNo',
    appId: '1:389651563164:web:b39bcb59eb37c1cb906359',
    messagingSenderId: '389651563164',
    projectId: 'e-tarabay',
    authDomain: 'e-tarabay.firebaseapp.com',
    storageBucket: 'e-tarabay.firebasestorage.app',
    measurementId: 'G-5Q5C9KSMER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUj9AbLbvn9G72jOQfh0Bkmf1nDsTmd5M',
    appId: '1:175084418339:android:30e037073b60f17d2ec896',
    messagingSenderId: '175084418339',
    projectId: 'e-tarabay-ffff9',
    storageBucket: 'e-tarabay-ffff9.firebasestorage.app',
    databaseURL: 'https://e-tarabay-ffff9-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFM_M4sbB53P2fV7YyjhFs_Uj6cJS1tzY',
    appId: '1:389651563164:ios:5ed86a68cadae1d4906359',
    messagingSenderId: '389651563164',
    projectId: 'e-tarabay',
    storageBucket: 'e-tarabay.firebasestorage.app',
    iosBundleId: 'com.example.eTarabay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFM_M4sbB53P2fV7YyjhFs_Uj6cJS1tzY',
    appId: '1:389651563164:ios:5ed86a68cadae1d4906359',
    messagingSenderId: '389651563164',
    projectId: 'e-tarabay',
    storageBucket: 'e-tarabay.firebasestorage.app',
    iosBundleId: 'com.example.eTarabay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8PJO6vZlY4CeRriyuOpcoxcuK6q0xLNo',
    appId: '1:389651563164:web:237a96d1510b85d4906359',
    messagingSenderId: '389651563164',
    projectId: 'e-tarabay',
    authDomain: 'e-tarabay.firebaseapp.com',
    storageBucket: 'e-tarabay.firebasestorage.app',
    measurementId: 'G-P064KYPP05',
  );
}
